### ISSUE TITLE
gatling-grpc 0.4.1 incompatible with with Gatling 3.2.0 

### ISSUE THREAD

**Issue by Colins-Git** [phiSgr/gatling-grpc#13]
**Describe the bug**
Unable to run with Gatling 3.2.0 

**To Reproduce**
Create a project that uses Gatling 3.2.0. 
Run the project. 

15:39:57.570 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.IncompatibleClassChangeError: class com.github.phisgr.gatling.grpc.check.StatusExtract$Materializer$ can not implement io.gatling.core.check.CheckMaterializer, because it is not an interface (io.gatling.core.check.CheckMaterializer is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.ea.mls.myclass.gatling.simulation.MySimulation.<init>(MySimulation.scala:20)
	... 19 common frames omitted
Wrapped by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.gatling.app.Runner.run0(Runner.scala:74)
	at io.gatling.app.Runner.run(Runner.scala:60)
	at io.gatling.app.Gatling$.start(Gatling.scala:73)
	at io.gatling.app.Gatling$.fromMap(Gatling.scala:41)
	at Engine$.delayedEndpoint$Engine$1(Engine.scala:11)
	at Engine$delayedInit$body.apply(Engine.scala:4)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at Engine$.main(Engine.scala:4)
	at Engine.main(Engine.scala)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.gatling.app.Runner.run0(Runner.scala:74)
	at io.gatling.app.Runner.run(Runner.scala:60)
	at io.gatling.app.Gatling$.start(Gatling.scala:73)
	at io.gatling.app.Gatling$.fromMap(Gatling.scala:41)
	at Engine$.delayedEndpoint$Engine$1(Engine.scala:11)
	at Engine$delayedInit$body.apply(Engine.scala:4)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at Engine$.main(Engine.scala:4)
	at Engine.main(Engine.scala)
Caused by: java.lang.IncompatibleClassChangeError: class com.github.phisgr.gatling.grpc.check.StatusExtract$Materializer$ can not implement io.gatling.core.check.CheckMaterializer, because it is not an interface (io.gatling.core.check.CheckMaterializer is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.ea.mls.myclass.gatling.simulation.MySimulation.<init>(MySimulation.scala:20)
	... 19 more

**Expected behavior**
The code to run

**Environment:**
 - OS: Windows
 - Java: 
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+12-b304.10)
OpenJDK 64-Bit Server VM (build 11.0.3+12-b304.10, mixed mode)

 - Version: 0.4.1

**Additional context**
It seems like 
package io.gatling.core.check
trait CheckMaterializer[T, C <: io.gatling.core.check.Check[R], R, P] extends scala.AnyRef 
has changed to 
package io.gatling.core.check
abstract class CheckMaterializer[T, C <: Check[R], R, P](specializer: Specializer[C, R]) 
This may be causing compilation issues.

**Comment by phiSgr** [comment]
Oh I didn't know about the binary incompatibility from 3.1.3 to 3.2.0. Could you use Gatling 3.1.3 for now?

**Comment by Colins-Git** [comment]
I already downgraded to Gatling 3.1.3 for now and have no issues staying on Gatling 3.1.3. 
I created the bug to inform you of the incompatibility, so you can develop a fix on your own timeline.  Thanks for any and all help addressing this issue and creating this helpful tool.

**Comment by Colins-Git** [comment]
Wow thanks for fixing this so quickly!
