### ISSUE TITLE
Better netty exception handling for bad address lookups

### ISSUE THREAD

**Issue by fusioned** [phiSgr/gatling-grpc#18]
**Is your feature request related to a problem? Please describe.**
Sometimes there are DNS issues with the endpoint, whether it is
- unable to resolve name
- cannot connect
- just simply wrongly specified by the user

These appear in Gatling as exceptions in the log. Now it seems that `io.netty` / `io.grpc` use JUL for logging (but I have been able to use the slf4j-jul-bridge to force it to use Logback).

These look like:

```
17:27:59.757 [DEBUG] i.g.c.c.i.o.OpenWorkload - Start user #8
Nov 20, 2019 5:27:59 PM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl handleErrorInSyncContext
WARNING: [Channel<15>: (notlocalhost:8080)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host notlocalhost, cause=java.lang.RuntimeException: java.net.UnknownHostException: notlocalhost
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:414)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:252)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: nolocalhost
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:634)
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:382)
	... 5 more
}
17:27:59.765 [DEBUG] i.g.c.a.Exit - End user #8
```

The end summary states:
```
> grpcStatusCode.find.is(OK), but actually found UNAVAILABLE         10 (100.0%)
```

which is almost the same as if an invalid request was made, rather than bad endpoint address, so diagnosing failures is unnecessarily difficult.

I have been trying to unroll the stack trace to see where we could catch these errors, to no success so far.

**Describe the solution you'd like**
Ideally, catch DNS resolution exceptions if possible, and categorise accordingly so the error summary can look something like 
```
2019-11-20 18:03:39                                           4s elapsed
---- Requests ------------------------------------------------------------------
> xyz                                     (OK=0      KO=10    )
---- Errors --------------------------------------------------------------------
> Could not resolve host: notlocalhost.io
> Timed out, could not connect to host: myendpoint
```

In the logs - a simpler entry
```
[WARN] Unable to resolve host: notlocalhost 
```

**Comment by phiSgr** [comment]
This seems to be too specific to isolate. I think the logging added when I fix #17 will suffice.

**Comment by phiSgr** [comment]
An example log:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Wrong server: KO grpcStatusCode.find.is(UNIMPLEMENTED), but actually found UNAVAILABLE
=========================
Session:
Session(Example,48,1575395360803,Map(s -> Server, username -> user_q, gatling.grpc.channel.60b1b2ef-98b6-4035-89a2-3ad50591ce32 -> ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=195, target=notlocalhost:9999}}, token -> mlxezZgzBf, gatling.grpc.channel -> ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=183, target=localhost:8080}}),0,OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$379/1893304297@72820266)
=========================
gRPC response:
status=
UNAVAILABLE, description: NameResolver returned an empty list
trailers=
Metadata()
<<<<<<<<<<<<<<<<<<<<<<<<<
```

I hope "NameResolver returned an empty list" should be good enough.

**Comment by fusioned** [comment]
Much appreciated! Thanks for working on this, I will check this out.

**Comment by fusioned** [comment]
It's definitely much better. What would also be useful if the `UnknownHostException` could be caught, so it does not pollute the rest of the output. This is currently what it looks like:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
my-test-create-call: KO grpcStatusCode.find.is(OK), but actually found UNAVAILABLE
=========================
Session:
Session(Create thing,8,1576694086918,Map(name -> loadtest-item-81C3pMWEeZ, request -> 86d4c209-b000-4d8a-b8a4-174a6982dba8, gatling.grpc.channel -> ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=15, target=nolocalhost:8080}}),0,OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$476/0x0000000100505840@77572b2)
=========================
gRPC response:
status=
UNAVAILABLE, description: Unable to resolve host nolocalhost
java.lang.RuntimeException: java.net.UnknownHostException: nolocalhost
trailers= 
Metadata()
<<<<<<<<<<<<<<<<<<<<<<<<<
18:34:46.927 [DEBUG] i.g.c.a.Exit - End user #8
18:34:46.927 [DEBUG] i.g.c.c.i.Injector - End user #8
18:34:47.419 [DEBUG] i.g.c.c.i.o.OpenWorkload - Injecting 1 users in scenario Create and verify Schedule, continue=false
18:34:47.420 [INFO ] i.g.c.c.i.Injector - StoppedInjecting
18:34:47.420 [DEBUG] i.g.c.c.i.o.OpenWorkload - Start user #9
Dec 18, 2019 6:34:47 PM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl handleErrorInSyncContext
WARNING: [Channel<17>: (nolocalhost:8080)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host nolocalhost, cause=java.lang.RuntimeException: java.net.UnknownHostException: nolocalhost
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:414)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:252)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: nolocalhost
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:634)
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:382)
	... 5 more
}
```
