### ISSUE TITLE
Error - There were no requests sent during the simulation, reports won't be generated

### ISSUE THREAD

**Issue by indusbull** [phiSgr/gatling-grpc#2]
Thanks for sharing grpc plugin. I have been trying to test my simple grpc service but it throws below exception. I am not able to figure out the exact issue. Help would be appreciated -

```
java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated
[error]         at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:48)
[error]         at io.gatling.app.RunResultProcessor.generateReports(RunResultProcessor.scala:76)
[error]         at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:55)
[error]         at io.gatling.app.Gatling$.start(Gatling.scala:68)
[error]         at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
[error]         at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error]         at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error]         at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Simulation GrpcLoadTestSimlulation failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error]         com.vz.security.sso.load.GrpcLoadTestSimlulation
[error] (Gatling / testOnly) sbt.TestsFailedException: Tests unsuccessful
```

And this is my test code - 

```
val gatlingVersion =  "2.3.1"
libraryDependencies ++= Seq(
  "io.gatling.highcharts" % "gatling-charts-highcharts" % gatlingVersion % "test",
  "io.gatling" % "gatling-test-framework" % gatlingVersion % "test",
  "com.github.phisgr" %% "gatling-grpc" % "0.1.0" % "test"
)
enablePlugins(GatlingPlugin)
```

```
class GrpcLoadTestSimlulation extends Simulation {

  val grpcConf = grpc(ManagedChannelBuilder.forAddress("grpcHost", grpcPort).usePlaintext())

  val payload = Map(
    ("userID", "tets")
  )

  val scoreRequest: ScoreRequest = ScoreRequest(fields = payload)

  val s = scenario("test")
    .exec(setUpGrpc)
      exec(
        grpc("Register")
          .rpc(ScoreServiceGrpc.METHOD_GET_SCORE)
          .payload(ScoreRequest)
          .check(
            statusCode is Status.Code.OK
          )
      )


  setUp(
    s.inject(rampUsers(100) over (1 minutes))
  ).protocols(grpcConf)
}
```

**Comment by phiSgr** [comment]
Maybe it is because the `.` that chains the `exec(` and the `.exec(setUpGrpc)` is missing.

**Comment by Kannanind** [comment]
how to eliminate this issue ?
