### ISSUE TITLE
java.lang.invoke.WrongMethodTypeException: expected (Metadata,int)Object but found (Metadata,int)byte[]

### ISSUE THREAD

**Issue by andrewoma** [phiSgr/gatling-grpc#25]
**Describe the bug**
When using Java generated grpc stubs it works, but logging of payloads fails

**To Reproduce**
```
package simulations

import com.github.phisgr.gatling.grpc.Predef._
import com.foo.grpc.{CoreMerchantRequest, MerchantServiceGrpc}
import io.gatling.core.Predef._
import io.gatling.core.scenario.Simulation
// stringToExpression is hidden because we have $ in GrpcDsl
import io.gatling.core.Predef.{stringToExpression => _, _}
import io.gatling.core.session.Expression
import io.grpc.Status

import scala.util.Random

class FooSimulation extends Simulation {

  val grpcConf = grpc(managedChannelBuilder(name = "localhost", port = 8300).usePlaintext())

  val coreMerchantRefFeeder = Iterator.continually(Map("coreMerchantRef" -> (Random.alphanumeric.take(30).mkString)))

  object CreateCoreMerchant {

    val createCoreMerchant = exec(
      grpc("Create Core Merchant")
        .rpc(MerchantServiceGrpc.getCreateCoreMerchantMethod)
        .payload(Templates.template)
        .check(statusCode is Status.Code.OK))
  }

  val scn = scenario("Setup Merchant")
    .feed(coreMerchantRefFeeder)
    .exec(CreateCoreMerchant.createCoreMerchant)

  setUp(scn.inject(atOnceUsers(1)).protocols(grpcConf))
}

object Templates {
  val template: Expression[CoreMerchantRequest] = (session: Session) =>
    for {
      coreMerchantRef <- session("coreMerchantRef").validate[String]
    } yield CoreMerchantRequest.newBuilder().setCoreRef(coreMerchantRef).build()
}
```

**Expected behavior**
The payload to be logged and no exceptions raised

**Environment:**
 - OS: OSX
 - Java: `openjdk version "11.0.5" 2019-10-15 LTS` (Tried 14 too)
 - Version: `gatling-grpc_2.12:0.8.1`

**Additional context**
Stack trace:
```
12:15:58.599 [GatlingSystem-akka.actor.default-dispatcher-6] ERROR akka.dispatch.TaskInvocation - expected (Metadata,int)Object but found (Metadata,int)byte[]
java.lang.invoke.WrongMethodTypeException: expected (Metadata,int)Object but found (Metadata,int)byte[]
        at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:484)
        at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:493)
        at com.github.phisgr.gatling.grpc.Reflections.value(Reflections.java:51)
        at com.github.phisgr.gatling.grpc.util.package$GrpcStringBuilder$.appendMetadata$extension(package.scala:80)
        at com.github.phisgr.gatling.grpc.util.package$GrpcStringBuilder$.appendHeaders$extension(package.scala:65)
        at com.github.phisgr.gatling.grpc.util.package$GrpcStringBuilder$.appendRequest$extension(package.scala:24)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.dump$1(GrpcCallAction.scala:178)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.run(GrpcCallAction.scala:189)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by phiSgr** [comment]
Thanks for providing the stack trace. I used reflections to access private methods to log the headers. The reflection failed because that private method changed. I will fix it in the next release.

**Comment by andrewoma** [comment]
Thanks very much!
