### ISSUE TITLE
StatusRuntimeException: UNKNOWN: Exception was thrown by handler.

### ISSUE THREAD

**Issue by mcopjan** [phiSgr/gatling-grpc#45]
Hi @phiSgr, my apologies for creating this question ticket (I know I am not supposed to), but I spent extensive amount of time to try to L&P my local gRPC service and although I went through https://medium.com/@georgeleung_7777/a-demo-of-gatling-grpc-bc92158ca808 and I think I am very close I cannot get it quite working 

I am using insecure connection to my service which is being hosted on :6000 (I can communicate to this service using RCP client)

![image](https://user-images.githubusercontent.com/20699180/109500506-42d2fb80-7a8e-11eb-8262-141940e9aad5.png)

when using the same proto file 
[coingecko.proto.zip](https://github.com/phiSgr/gatling-grpc/files/6061668/coingecko.proto.zip)

and 
```
class BasicItSimulation extends Simulation {

val grpcConf = grpc(managedChannelBuilder(name = "localhost", port = 6000).usePlaintext())
    .warmUpCall(ExchangeServiceGrpc.METHOD_STORE_EXCHANGE, StoreExchangeRequest.defaultInstance)

  val request = grpc("store exchange request")
    .rpc(ExchangeServiceGrpc.METHOD_STORE_EXCHANGE)
    .payload(StoreExchangeRequest.defaultInstance)

  val scn = scenario("Store Exchange")
    .exec(request)
  setUp(scn.inject(atOnceUsers(1)).protocols(grpcConf))
}
```

from https://github.com/phiSgr/gatling-grpc-sbt-demo

I am getting

```
sbt gatling-it:test
[info] welcome to sbt 1.4.3 (Oracle Corporation Java 1.8.0_281)
[info] loading global plugins from /Users/martinco/.sbt/1.0/plugins
[info] loading settings for project phisgr_gatling-grpc-sbt-demo-build-build-build from metals.sbt ...
[info] loading project definition from /Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/project/project/project
[info] loading settings for project phisgr_gatling-grpc-sbt-demo-build-build from metals.sbt ...
[info] loading project definition from /Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/project/project
[success] Generated .bloop/phisgr_gatling-grpc-sbt-demo-build-build.json
[success] Total time: 0 s, completed 01-Mar-2021 12:35:03
[info] loading settings for project phisgr_gatling-grpc-sbt-demo-build from metals.sbt,plugins.sbt,scalapb.sbt ...
[info] loading project definition from /Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/project
[success] Generated .bloop/phisgr_gatling-grpc-sbt-demo-build.json
[success] Total time: 0 s, completed 01-Mar-2021 12:35:04
[info] loading settings for project phisgr_gatling-grpc-sbt-demo from build.sbt ...
[info] set current project to phisgr_gatling-grpc-sbt-demo (in build file:/Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/)
12:35:06.366 [pool-1-thread-1] INFO io.gatling.core.config.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
12:35:06.757 [GatlingSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
12:35:07.045 [pool-1-thread-1] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
12:35:07.054 [pool-1-thread-1] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
12:35:07.068 [pool-1-thread-1] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
12:35:07.068 [pool-1-thread-1] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
12:35:07.074 [pool-1-thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
12:35:07.075 [pool-1-thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
12:35:07.088 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
12:35:07.090 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
12:35:07.090 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
12:35:07.091 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
12:35:07.092 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
12:35:07.092 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
12:35:07.093 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
12:35:07.093 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
12:35:07.094 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9 => phisgr_gatling-grpc-sbt-demo / Gatling-it / executeTests 0s
12:35:07.094 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
12:35:07.094 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
12:35:07.094 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/z1/tksppdzn3lzb06md9r087_jjw7_b6t/T (java.io.tmpdir)| => phisgr_gatling-grpc-sbt-demo / Gatling-it / executeTests 0s
12:35:07.095 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
12:35:07.096 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1073741824 bytes
12:35:07.096 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
12:35:07.097 [pool-1-thread-1] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
12:35:07.097 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
12:35:07.104 [pool-1-thread-1] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
12:35:07.429 [pool-1-thread-1] INFO com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$ - Making warm up call with method grpc.coingecko.ExchangeService/StoreExchange phisgr_gatling-grpc-sbt-demo / Gatling-it / executeTests 1s
12:35:07.531 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
12:35:07.531 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
12:35:07.537 [grpc-default-executor-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
12:35:07.539 [grpc-default-executor-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
12:35:07.540 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@68928e6dphisgr_gatling-grpc-sbt-demo / Gatling-it / executeTests 1s
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 10
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 10
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
12:35:07.614 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
12:35:07.634 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 22840 (auto-detected)
12:35:07.637 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
12:35:07.637 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
12:35:07.639 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
12:35:07.640 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
12:35:07.642 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
12:35:07.660 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
12:35:07.660 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
12:35:07.660 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
12:35:07.675 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
12:35:07.675 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
12:35:07.675 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
12:35:07.675 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
12:35:07.675 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
12:35:07.695 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
12:35:07.702 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041mo / Gatling-it / executeTests 1s
12:35:07.713 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=98304, MAX_HEADER_LIST_SIZE=32768}
12:35:07.714 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND SETTINGS: ack=true
12:35:07.729 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=65537demo / Gatling-it / executeTests 1s
12:35:07.730 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] INBOUND SETTINGS: ack=true
12:35:07.732 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:6000, :path: /grpc.coingecko.ExchangeService/StoreExchange, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.30.2, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
12:35:07.739 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=5 bytes=0000000000 / executeTests 1s
12:35:07.743 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, date: Mon, 01 Mar 2021 12:35:06 GMT, content-type: application/grpc, server: Kestrel, content-length: 0, grpc-status: 2, grpc-message: Exception was thrown by handler.] padding=0 endStream=true
12:35:07.749 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND RST_STREAM: streamId=3 errorCode=8atling-grpc-sbt-demo / Gatling-it / executeTests 1s
12:35:07.751 [pool-1-thread-1] DEBUG com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$ - Couldn't execute warm up request
io.grpc.StatusRuntimeException: UNKNOWN: Exception was thrown by handler.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:110)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2(grpcProtocol.scala:73)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2$adapted(grpcProtocol.scala:65)
        at scala.Option.foreach(Option.scala:407)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.<init>(grpcProtocol.scala:65)
        at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol.createComponents(grpcProtocol.scala:159)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$$anon$1.$anonfun$newComponents$1(grpcProtocol.scala:113)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:72)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:74)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:74)
        at com.github.phisgr.gatling.grpc.request.Call.<init>(Call.scala:34)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction.<init>(GrpcCallAction.scala:27)
        at com.github.phisgr.gatling.grpc.action.GrpcCallActionBuilder.build(GrpcCallActionBuilder.scala:21)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:51)
        at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:100)
        at io.gatling.core.scenario.SimulationParams.buildScenario(Simulation.scala:170)
        at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:174)
        at scala.collection.immutable.List.map(List.scala:293)
        at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:174)
        at io.gatling.app.Runner.run0(Runner.scala:82)
        at io.gatling.app.Runner.run(Runner.scala:52)
        at io.gatling.app.Gatling$.start(Gatling.scala:80)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
        at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
        at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
        at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
12:35:07.753 [gatling-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xc7f22ba9, L:/127.0.0.1:49160 - R:localhost/127.0.0.1:6000] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=emo / Gatling-it / executeTests 1s
Simulation BasicItSimulation started...
12:35:07.766 [GatlingSystem-akka.actor.default-dispatcher-5] INFO io.gatling.core.stats.writer.ConsoleDataWriter - Initializing
12:35:07.766 [GatlingSystem-akka.actor.default-dispatcher-6] INFO io.gatling.core.stats.writer.LogFileDataWriter - Initializing
12:35:07.773 [GatlingSystem-akka.actor.default-dispatcher-5] INFO io.gatling.core.stats.writer.ConsoleDataWriter - Initialized
12:35:07.777 [GatlingSystem-akka.actor.default-dispatcher-6] INFO io.gatling.core.stats.writer.LogFileDataWriter - Initialized
12:35:07.793 [GatlingSystem-akka.actor.default-dispatcher-7] DEBUG io.gatling.core.controller.inject.open.OpenWorkload - Injecting 1 users in scenario Store Exchange, continue=falseng-grpc-sbt-demo / Gatling-it / executeTests 1s
12:35:07.797 [GatlingSystem-akka.actor.default-dispatcher-7] INFO io.gatling.core.controller.inject.Injector - Scenario Store Exchange has finished injecting
12:35:07.797 [GatlingSystem-akka.actor.default-dispatcher-7] INFO io.gatling.core.controller.inject.Injector - Injecting is done
12:35:07.803 [gatling-1-3] DEBUG io.gatling.core.controller.inject.open.OpenWorkload - Start user #1
12:35:07.807 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
12:35:07.808 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041mo / Gatling-it / executeTests 1s
12:35:07.809 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=98304, MAX_HEADER_LIST_SIZE=32768}
12:35:07.809 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND SETTINGS: ack=true
12:35:07.809 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=65537
12:35:07.809 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] INBOUND SETTINGS: ack=true
12:35:07.810 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:6000, :path: /grpc.coingecko.ExchangeService/StoreExchange, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.30.2, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
12:35:07.810 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=5 bytes=0000000000
12:35:07.812 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, date: Mon, 01 Mar 2021 12:35:06 GMT, content-type: application/grpc, server: Kestrel, content-length: 0, grpc-status: 2, grpc-message: Exception was thrown by handler.] padding=0 endStream=true
12:35:07.826 [gatling-1-3] INFO com.github.phisgr.gatling.grpc.action.GrpcCallAction - Request 'store exchange request' failed for user 1: grpcStatusCode.find.is(OK), but actually found UNKNOWNdemo / Gatling-it / executeTests 1s
12:35:07.911 [gatling-1-3] DEBUG com.github.phisgr.gatling.grpc.action.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>-sbt-demo / Gatling-it / executeTests 2s
Request:
store exchange request: KO grpcStatusCode.find.is(OK), but actually found UNKNOWN
=========================
Session:
Session(Store Exchange,1,Map(gatling.grpc.channel -> ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=5, target=localhost:6000}}),OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$358/1437581789@4b818b87,io.netty.channel.nio.NioEventLoop@87133a6)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=

=========================
gRPC response:
status=
UNKNOWN, description: Exception was thrown by handler.
trailers=
date: Mon, 01 Mar 2021 12:35:06 GMT
content-type: application/grpc
server: Kestrel
content-length: 0
<<<<<<<<<<<<<<<<<<<<<<<<<
12:35:07.911 [gatling-1-3] DEBUG io.gatling.core.action.Exit - End user #1
12:35:07.914 [gatling-1-5] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8659341b, L:/127.0.0.1:49161 - R:localhost/127.0.0.1:6000] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=emo / Gatling-it / executeTests 2s
12:35:07.915 [GatlingSystem-akka.actor.default-dispatcher-7] DEBUG io.gatling.core.controller.inject.Injector - End user #Store Exchange
12:35:07.915 [GatlingSystem-akka.actor.default-dispatcher-7] INFO io.gatling.core.controller.inject.Injector - All users of scenario Store Exchange are stopped
12:35:07.916 [GatlingSystem-akka.actor.default-dispatcher-7] INFO io.gatling.core.controller.inject.Injector - Stopping
12:35:07.916 [GatlingSystem-akka.actor.default-dispatcher-6] INFO io.gatling.core.controller.Controller - Injector has stopped, initiating graceful stop

================================================================================
2021-03-01 12:35:07                                           0s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=1     )
> store exchange request                                   (OK=0      KO=1     )
---- Errors --------------------------------------------------------------------
> grpcStatusCode.find.is(OK), but actually found UNKNOWN              1 (100.0%)

---- Store Exchange ------------------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 1     
================================================================================

12:35:07.931 [GatlingSystem-akka.actor.default-dispatcher-4] INFO io.gatling.core.controller.Controller - StatsEngineStopped
Simulation BasicItSimulation completed in 0 seconds
12:35:07.933 [gatling-1-5] DEBUG io.netty.buffer.PoolThreadCache - Freed 7 thread-local buffer(s) from thread: gatling-1-5
12:35:07.933 [gatling-1-2] DEBUG io.netty.buffer.PoolThreadCache - Freed 7 thread-local buffer(s) from thread: gatling-1-2
Parsing log file(s)...
12:35:07.996 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Collected ArrayBuffer(/Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/target/gatling-it/basicitsimulation-20210301123507393/simulation.log) from basicitsimulation-20210301123507393
12:35:08.006 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - First pass
12:35:08.014 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - First pass done: read 4 lines
12:35:08.022 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Second pass
12:35:08.052 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Second pass: read 4 lines
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                          1 (OK=0      KO=1     )
> min response time                                     12 (OK=-      KO=12    )
> max response time                                     12 (OK=-      KO=12    )
> mean response time                                    12 (OK=-      KO=12    )
> std deviation                                          0 (OK=-      KO=0     )
> response time 50th percentile                         12 (OK=-      KO=12    )
> response time 75th percentile                         12 (OK=-      KO=12    )
> response time 95th percentile                         12 (OK=-      KO=12    )
> response time 99th percentile                         12 (OK=-      KO=12    )
> mean requests/sec                                      1 (OK=-      KO=1     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 1 (100%)
---- Errors --------------------------------------------------------------------
> grpcStatusCode.find.is(OK), but actually found UNKNOWN              1 (100.0%)
================================================================================

Reports generated in 0s.
Please open the following file: /Users/martinco/Work/phiSgr_gatling-grpc-sbt-demo/target/gatling-it/basicitsimulation-20210301123507393/index.html
[info] Simulation BasicItSimulation successful.
[info] Simulation(s) execution ended.
[success] Total time: 4 s, completed 01-Mar-2021 12:35:08
```
Could you please elaborate on the above. Much appreciated. Thanks

**Comment by mcopjan** [comment]
Right, I can answer my question now. My problem was on my gRCP server side where by sending **StoreExchangeRequest.defaultInstance** due to a nested structure of incoming request 

```

syntax = "proto3";
package grpc.coingecko;

service ExchangeService {
  // Sends a greeting
  rpc StoreExchange (StoreExchangeRequest) returns (StoreExchangeResponse);
}
message Exchange {
    string mongo_id =1;
    string year_established =2;
    string country =3;
    string description =4;
    string url =5;
    string image =6;
    string has_trading_incentive =7;
    string trust_score =8;
    string trust_score_rank =9;
    string trade_volume_24h_btc_normalized =10;
    string id =11;
    string name =12;
}

message StoreExchangeRequest {
    Exchange exchange=1;
    }

message StoreExchangeResponse {
    Exchange result=1;
    }
```

my Exchange object was set to null and this was not properly handled on server side.

Thanks @phiSgr for this great project!

**Comment by phiSgr** [comment]
If all questions were as detailed as yours I wouldn't forbid questions here.

BTW as you may infer from the `DEBUG` log level, the warm up request failing does not affect the execution of the load test.

**Comment by mcopjan** [comment]
@phiSgr seeing some previous questions I kind of understand your reasons. People tend to choose the easiest way, create a ticket and wait for someone to sort it out. I would still not completely ban it. Although the problem I faced was ultimately caused by my environment (unhandled server errors), I could not figure it out for the life of me. Sometimes another pair of eyes can make a huge difference.
The main problem here was that I was not very familiar with Scala neither with gatling.


This did the trick, inner object inside StoreExchangeRequest was initialised before sending to the server + better error handling on server side

```
al grpcConf = grpc(managedChannelBuilder(name = "localhost", port = 6000).usePlaintext())
    

  val request = grpc("store exchange request")
    .rpc(ExchangeServiceGrpc.METHOD_STORE_EXCHANGE)
    .payload(StoreExchangeRequest.defaultInstance.updateExpr(
                _.exchange.name :~ "test"
              ))

  val scn = scenario("Store Exchange")
    .exec(request)
  setUp(scn.inject(atOnceUsers(1)).protocols(grpcConf))
}
```

**Comment by phiSgr** [comment]
Simply write `StoreExchangeRequest(exchange=Exchange(name="test"))` for a static object.
`updateExpr` is necessary only when you need to use the [session](https://gatling.io/docs/current/session/session_api/).
