### ISSUE TITLE
`master` Cannot be Executed in Gatling Enterprise

### ISSUE THREAD

**Issue by jGleitz** [phiSgr/gatling-grpc#63]
**Describe the bug**
The current `master` cannot be executed in Gatling Enterprise. All calls fail with an error like this:

```
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
```

<details>
<summary>Full Stack Trace</summary>

```
Aug 19, 2022 12:47:01 PM io.grpc.internal.ManagedChannelImpl$2 uncaughtException
SEVERE: [Channel<3>: (rtc-resource-manager.services-stage.goto.com:6565)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
        at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
        at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
        at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:412)
        at io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:980)
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
        at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
        at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:977)
        at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:919)
        at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2(grpcProtocol.scala:76)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2$adapted(grpcProtocol.scala:68)
        at scala.Option.foreach(Option.scala:437)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.<init>(grpcProtocol.scala:68)
        at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol.createComponents(grpcProtocol.scala:168)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$$anon$1.$anonfun$newComponents$1(grpcProtocol.scala:116)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:71)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:73)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:73)
        at com.github.phisgr.gatling.grpc.request.Call.<init>(Call.scala:19)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction.<init>(GrpcCallAction.scala:28)
        at com.github.phisgr.gatling.grpc.action.GrpcCallActionBuilder.build(GrpcCallActionBuilder.scala:19)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:55)
        at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:94)
        at io.gatling.core.scenario.SimulationParams.buildScenario(Simulation.scala:197)
        at io.gatling.core.scenario.SimulationParams.$anonfun$scenarioFlows$1(Simulation.scala:201)
        at scala.collection.immutable.List.map(List.scala:250)
        at io.gatling.core.scenario.SimulationParams.scenarioFlows(Simulation.scala:201)
        at io.gatling.app.Runner.run(Runner.scala:74)
        at io.gatling.app.Gatling$.start(Gatling.scala:90)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:52)
        at io.gatling.app.Gatling$.main(Gatling.scala:40)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

</details>

**To Reproduce**
Build the current `master`, use it in any Gatling test and execute in on Gatling Enterprise. All requests will be reported as failing with status `INTERNAL`. The injector logs will contain the exception above.

**Expected behavior**
Everything works.

**Additional context**
This is a regression against the latest published version. ~I think the root cause is that the Gatling Maven plugin removes all files from `META-INF` when building the fat jar with `gatling:enterprisePackage`. It seems that some code change made loading that file necessary.~

**Workaround**
Specify `.defaultLoadBalancingPolicy("round_robin")` on the `ManagedChannelBuilder` that you pass to `com.github.phisgr.gatling.grpc.Predef.grpc`.

**Comment by phiSgr** [comment]
Do you have a minimal reproducible example? A fat jar that fails to run and the project that creates it would be great.

**Comment by jGleitz** [comment]
I tried all day to come up with a minimal reproducer. However, I failed so far. That probably means that this problem has to do with our specific classpath. And it maybe also means that this project is not to blame, and the fact that the problem only started occurring after we updated the library may just have been bad luck.
