### ISSUE TITLE
java.lang.IllegalAccessError while running tests

### ISSUE THREAD

**Issue by inenashev** [phiSgr/gatling-grpc#67]
Hi, getting error while trying to use this plugin, and I do not understand whats wrong:

```
java.lang.IllegalAccessError: tried to access method io.gatling.core.session.SessionPrivateAttributes$.PrivateAttributePrefix()Ljava/lang/String; from class com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$
	at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$.<clinit>(grpcProtocol.scala:25)
	at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol$.apply$default$3(grpcProtocol.scala:149)
	at com.github.phisgr.gatling.grpc.GrpcDsl.grpc(GrpcDsl.scala:33)
	at com.github.phisgr.gatling.grpc.GrpcDsl.grpc$(GrpcDsl.scala:33)
	at com.github.phisgr.gatling.grpc.Predef$.grpc(Predef.scala:6)
	at tchk_dev_user_pb.<init>(tchk_dev_user_pb.scala:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.gatling.app.SimulationClass$Scala.params(SimulationClass.scala:31)
	at io.gatling.app.Runner.run(Runner.scala:53)
	at io.gatling.app.Gatling$.start(Gatling.scala:91)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:53)
	at io.gatling.app.Gatling$.fromSbtTestFramework(Gatling.scala:49)
	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

versions:
gatling-grpc - 0.14
gatling - 3.8.4

**Comment by phiSgr** [comment]
Downgrade to 3.8.3 for now

**Comment by inenashev** [comment]
Thanks, this helped

**Comment by phiSgr** [comment]
0.15.0, built against Gatling 3.8.4, published
