### ISSUE TITLE
Incompatible with Gatling v3.9.0

### ISSUE THREAD

**Issue by jGleitz** [phiSgr/gatling-grpc#72]
**Describe the bug**
The latest release cannot be used with Gatling v3.9.0

**To Reproduce**
Run a simulation using the dynamic channel feature (probably also happens without dynamic channels) against Gatling 3.9.0. Gives:

```
13:29:45.471 <                   gatling-1-2> [  i.n.u.concurrent.AbstractEventExecutor]  WARN: A task raised an exception. Task: io.gatling.core.action.Action$$Lambda$618/0x00000008012a3870@5f2c111c 
java.lang.NoSuchMethodError: 'io.netty.channel.ChannelFactory io.gatling.netty.util.Transports.newSocketChannelFactory(boolean)'
	at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$.setEventLoopGroup(grpcProtocol.scala:127)
	at com.github.phisgr.gatling.grpc.action.SetDynamicChannel.execute(dynamicChannel.scala:29)
	at io.gatling.core.action.Action.$anonfun$$bang$1(Action.scala:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
Everything works :)

**Environment:**
 - OS: Ubuntu 22.10
 - Java: result of `java -version
```
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```
 - Version: 0.15.1

**Additional context**
The problem seems to be that `io.netty.channel.ChannelFactory io.gatling.netty.util.Transports.newSocketChannelFactory` now takes two parameters:  `boolean useNativeTransport, boolean useIoUring`. The fix is easy: Pass through `NettyConfiguration.useIoUring`. 

_However_, that would break compatibility with Gatling v3.8.x. What’s the policy of this project? Does it only support latest Gatling? Or should we introduce some reflection magic to ensure compatibility with more versions?

**Comment by phiSgr** [comment]
> Does it only support latest Gatling?

Yes

**Comment by slandelle** [comment]
@jGleitz Indeed, several internals have changed in Gatling 3.9.0. This one is only the first one.

@phiSgr I've just sent a PR: https://github.com/phiSgr/gatling-grpc/pull/73

**Comment by micheljung** [comment]
@phiSgr are you still around? Could you merge this? :)

**Comment by pluttrell** [comment]
+1

**Comment by phiSgr** [comment]
Not that I expect anyone to care, but if you're curious, my life is a mess (well, or to be honest, a bigger mess than it would've been) thanks to the tardiness of IRCC. It's hard to care about software versions when one's life is put on hold by bureaucracy.
