### ISSUE TITLE
Instructions don't work with the latest version of the Gatling Demo project

### ISSUE THREAD

**Issue by pluttrell** [phiSgr/gatling-grpc#77]
These instructions (https://medium.com/@georgeleung_7777/a-demo-of-gatling-grpc-bc92158ca808) fail with the latest version version of [The Gatling gRPC demo project](https://github.com/gatling/gatling-sbt-plugin-demo).

The first run of `sbt gatling-it:test` fails with:
```
[error] java.lang.reflect.InvocationTargetException
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error] 	at io.gatling.app.SimulationClass$Scala.params(SimulationClass.scala:31)
[error] 	at io.gatling.app.Runner.load(Runner.scala:72)
[error] 	at io.gatling.app.Runner.run(Runner.scala:57)
[error] 	at io.gatling.app.Gatling$.start(Gatling.scala:89)
[error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)
[error] 	at io.gatling.app.Gatling$.fromSbtTestFramework(Gatling.scala:47)
[error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: java.lang.NoClassDefFoundError: io/gatling/core/check/FindCheckBuilder
[error] 	at com.github.phisgr.gatling.grpc.check.GrpcCheckSupport.$init$(GrpcCheckSupport.scala:11)
[error] 	at com.github.phisgr.gatling.grpc.Predef$.<clinit>(Predef.scala:5)
[error] 	at computerdatabase.BasicItSimulation.<init>(BasicItSimulation.scala:11)
[error] 	... 17 more
[error] Caused by: java.lang.ClassNotFoundException: io.gatling.core.check.FindCheckBuilder
[error] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[error] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error] 	... 20 more
[error] Simulation BasicItSimulation failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error] 	computerdatabase.BasicItSimulation
[error] (Gatling-it / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Mar 7, 2023, 9:02:06 PM
```

**Comment by phiSgr** [comment]
If you want the demo project updated, open an issue at that repo instead.
