### ISSUE TITLE
v0.15.1 doesn't work with demo project

### ISSUE THREAD

**Issue by pluttrell** [phiSgr/gatling-grpc#78]
If you clone the [phiSgr/gatling-grpc-sbt-demo](https://github.com/phiSgr/gatling-grpc-sbt-demo) repo and run `sbt clean compile gatling-test:it` it works.

But if you upgrade to the latest version of gatling-grpc `0.15.1` by changing
```
libraryDependencies += "com.github.phisgr" %% "gatling-grpc" % "0.10.1" % "test,it"
```
to 
```
libraryDependencies += "com.github.phisgr" %% "gatling-grpc" % "0.15.1” % "test,it"
```

And run `sbt clean compile gatling-test:it` again it fails with this error:
```
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.phisgr:gatling-grpc_2.12:0.15.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/com.github.phisgr/gatling-grpc_2.12/0.15.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/phisgr/gatling-grpc_2.12/0.15.1/gatling-grpc_2.12-0.15.1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3484)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.phisgr:gatling-grpc_2.12:0.15.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/com.github.phisgr/gatling-grpc_2.12/0.15.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/phisgr/gatling-grpc_2.12/0.15.1/gatling-grpc_2.12-0.15.1.pom
[error] Total time: 1 s, completed Mar 7, 2023, 9:06:15 PM
```

**Comment by phiSgr** [comment]
https://github.com/phiSgr/gatling-grpc/blob/9398c4b889c630e8423af67de62d37d4e7490911/CHANGELOG.md?plain=1#L65
