### ISSUE TITLE
Exec after grpc action is not running

### ISSUE THREAD

**Issue by KirillSefirov** [phiSgr/gatling-grpc#80]
Hi, I'm pretty new to Gatling, and there is a problem. I wrote my tests and it works fine, but one thing that bothers me. For some reason any exec I write in scenario after grpc request is not running like it doesn't exist. 
Here is my code in Kotlin
```
val myScenario = scenario("scenario name")
        .exec(File1.firstGrpcAction)
        .exec(File2.secondGrpcAction)

fun firstGrpcAction(): GrpcCallActionBuilder<request, response> {
        return grpc("grpc name")
            .rpc(necessary method)
            .payload { request {
                payload1 = 111
            }}
            .header(header1, value)
            .header<String>(header2) {session: Session ->
                session.getString("value")!!
            }
            .check({ extract { it.allFields}.saveAs("info") }, { statusCode.`is`(OK) })
    }

val protocol = grpc(managedChannelBuilder(host, port)).shareChannel()
init {
        setUp(
            CommonScenario.myScenario.injectOpen(
                atOnceUsers(2)
            )
        )
            .protocols(Grpc.protocol)
            .maxDuration(60)
    }

```
second action is exactly the same. 
But it is not running. 
Even if i try 
val myScenario = scenario("scenario name")
        .exec(File1.firstGrpcAction)
        .exec{session -> 
                   println("SOMETHING")
session}

second exec doesn't print anything

**Comment by KirillSefirov** [comment]
Ah, right, if exec with print or for example http request will stand before grpc, then both actions are running perfectly

**Comment by phiSgr** [comment]
Could you show me your `simulation.log`?

Do you mind writing a minimal reproducer?

**Comment by KirillSefirov** [comment]
> Could you show me your `simulation.log`?
> 
> Do you mind writing a minimal reproducer?

Simulation log looks something like that, nothing interesting there
`RUN	something.tests.Debug	debug	1680862098919	 	3.9.2
USER	Group grpc test	START	1680862099988
USER	Group grpc test	START	1680862099988
REQUEST		requestname	1680862099996	1680862100054	KO	grpcResponse.find.exists preparation crashed: UNAUTHENTICATED: Invalid token: Expired JWT
REQUEST		requestname	1680862099996	1680862100055	KO	grpcResponse.find.exists preparation crashed: UNAUTHENTICATED: Invalid token: Expired JWT
`

About reproducer let me try to do it today. I'll use some open protos

**Comment by KirillSefirov** [comment]
@phiSgr I couldn't make it work with your proto file, guess I don't understand how to run the server. 
https://github.com/KirillSefirov/gatlingNoActionsAfterExec

But even with an error - it reproduces here. 

The only thing I noticed
- if I put localhost in protocol settings -> All execs are run. 
- if I put any IP address -> test run doesn't go to the third exec after the request. 

Just can't make this test work by myself unfortunately. I really hope it will be enough for you

**Comment by phiSgr** [comment]
> if I put any IP address -> test run doesn't go to the third exec after the request.

Could you provide the full command to reproduce this behaviour?

**Comment by KirillSefirov** [comment]
> I put that in the readme. 
But the fast version will be `sbt Gatling/test`

**Comment by phiSgr** [comment]
I assume you want me to run it without a server to connect to. 

In that case the `ManagedChannel` is stuck in the `CONNECTING` state.
Then the calls don't end, so of course the actions after the call won't run.

You can force the call to end by specifying a deadline.
https://github.com/phiSgr/gatling-grpc/blob/72ad2f6044dc37b34649cda30b3dcf106ce0b5b1/gatling-grpc-kt/src/gatling/kotlin/com/github/phisgr/example/KtThrottleSimulation.kt#L67

---

But this is not your problem I guess? Your `simulation.log` did [include failed requests](https://github.com/phiSgr/gatling-grpc/issues/80#issuecomment-1500147563).

```
REQUEST		requestname	1680862099996	1680862100054	KO	grpcResponse.find.exists preparation crashed: UNAUTHENTICATED: Invalid token: Expired JWT
REQUEST		requestname	1680862099996	1680862100055	KO	grpcResponse.find.exists preparation crashed: UNAUTHENTICATED: Invalid token: Expired JWT
```

---

I also tried running the tests connecting to localhost, or to another computer on the network. Can't reproduce. The test run as expected.

**Comment by phiSgr** [comment]
Consider providing:

- A better/less redacted version of your actual test script
- The full terminal output

**Comment by KirillSefirov** [comment]
Sorry for the delay, I enabled logback in my project, and that is the stacktrace I got for my launch. Code is pretty much the same, sends 1 request by 1 user with two execs that print "Before!!!.." and "After!!!...". Please check the trace, hope it shows what is necessary to understand why even my successful request is not shutting down at the end

`Simulation mygrpcstuff.Debug started...
2023-04-12T13:08:32.609Z debugAsking Controller to start
2023-04-12T13:08:32.614Z debugSetting up max duration
2023-04-12T13:08:32.616Z debugInitializing
2023-04-12T13:08:32.616Z debugInitializing
2023-04-12T13:08:32.616Z debugInitializing
2023-04-12T13:08:32.623Z debugInitialized
2023-04-12T13:08:32.627Z debugInitialized
2023-04-12T13:08:32.628Z debugInitialized
2023-04-12T13:08:32.638Z debugInjecting 1 users in scenario Group grpc test, continue=false
2023-04-12T13:08:32.639Z debugScenario io.gatling.core.scenario.Scenario@79c6d662 has finished injecting
2023-04-12T13:08:32.639Z debugAll scenarios have finished injecting
BEFORE GRPC!!!!!!!!!!!!!!!!!!!!!
2023-04-12T13:08:32.647Z debugStart user #1
2023-04-12T13:08:32.667Z debugFailed to connect to Graphite server located at: localhost/127.0.0.1:2003
2023-04-12T13:08:32.902Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2023-04-12T13:08:32.903Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2023-04-12T13:08:32.903Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2023-04-12T13:08:32.904Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=128, INITIAL_WINDOW_SIZE=65536, MAX_FRAME_SIZE=16777215}
2023-04-12T13:08:32.904Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND SETTINGS: ack=true
2023-04-12T13:08:32.904Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=2147418112
2023-04-12T13:08:32.914Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: myEndpoint, :path: my/Grpc/Method, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.51.0, eat: myEatToken, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2023-04-12T13:08:32.915Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=7 bytes=0000000002083a
2023-04-12T13:08:32.980Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND SETTINGS: ack=true
2023-04-12T13:08:33.024Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, server: awselb/2.0, date: Wed, 12 Apr 2023 13:08:33 GMT, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip, x-server-trace-id: a809f9f8dfd2d023] padding=0 endStream=false
2023-04-12T13:08:33.026Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND DATA: streamId=3 padding=0 endStream=false length=608 bytes=reponsebytes...
2023-04-12T13:08:33.026Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] OUTBOUND PING: ack=false bytes=1234
2023-04-12T13:08:33.029Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
2023-04-12T13:08:33.094Z debug[id: 0xcfe18ef5, L:/10.255.0.133:65435 - R:myEndpoint] INBOUND PING: ack=true bytes=1234
2023-04-12T13:08:33.099Z debugA task raised an exception. Task: com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener@23f17790
java.lang.NoClassDefFoundError: io/gatling/netty/util/StringBuilderPool
	at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.dump$1(GrpcCallAction.scala:155)
	at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.run(GrpcCallAction.scala:179)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.gatling.netty.util.StringBuilderPool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 common frames omitted
2023-04-12T13:08:33.654Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304913 gatling.debug.users.Group_grpc_test.waiting 0 1681304913 gatling.debug.users.Group_grpc_test.done 0 1681304913 gatling.debug.users.allUsers.active 1 1681304913 gatling.debug.users.allUsers.waiting 0 1681304913 gatling.debug.users.allUsers.done 0 1681304913 gatling.debug.allRequests.ok.count 1 1681304913 gatling.debug.allRequests.ok.min 444 1681304913 gatling.debug.allRequests.ok.max 445 1681304913 gatling.debug.allRequests.ok.mean 445 1681304913 gatling.debug.allRequests.ok.stdDev 0 1681304913 gatling.debug.allRequests.ok.percentiles50 445 1681304913 gatling.debug.allRequests.ok.percentiles75 445 1681304913 gatling.debug.allRequests.ok.percentiles95 445 1681304913 gatling.debug.allRequests.ok.percentiles99 445 1681304913 gatling.debug.allRequests.ko.count 0 1681304913 gatling.debug.allRequests.all.count 1 1681304913 gatling.debug.allRequests.all.min 444 1681304913 gatling.debug.allRequests.all.max 445 1681304913 gatling.debug.allRequests.all.mean 445 1681304913 gatling.debug.allRequests.all.stdDev 0 1681304913 gatling.debug.allRequests.all.percentiles50 445 1681304913 gatling.debug.allRequests.all.percentiles75 445 1681304913 gatling.debug.allRequests.all.percentiles95 445 1681304913 gatling.debug.allRequests.all.percentiles99 445 1681304913 gatling.debug.myMethod.ok.count 1 1681304913 gatling.debug.myMethod.ok.min 444 1681304913 gatling.debug.myMethod.ok.max 445 1681304913 gatling.debug.myMethod.ok.mean 445 1681304913 gatling.debug.myMethod.ok.stdDev 0 1681304913 gatling.debug.myMethod.ok.percentiles50 445 1681304913 gatling.debug.myMethod.ok.percentiles75 445 1681304913 gatling.debug.myMethod.ok.percentiles95 445 1681304913 gatling.debug.myMethod.ok.percentiles99 445 1681304913 gatling.debug.myMethod.ko.count 0 1681304913 gatling.debug.myMethod.all.count 1 1681304913 gatling.debug.myMethod.all.min 444 1681304913 gatling.debug.myMethod.all.max 445 1681304913 gatling.debug.myMethod.all.mean 445 1681304913 gatling.debug.myMethod.all.stdDev 0 1681304913 gatling.debug.myMethod.all.percentiles50 445 1681304913 gatling.debug.myMethod.all.percentiles75 445 1681304913 gatling.debug.myMethod.all.percentiles95 445 1681304913 gatling.debug.myMethod.all.percentiles99 445 1681304913 
2023-04-12T13:08:33.686Z debugFailed to connect to Graphite server located at: localhost/127.0.0.1:2003
2023-04-12T13:08:34.646Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304914 gatling.debug.users.Group_grpc_test.waiting 0 1681304914 gatling.debug.users.Group_grpc_test.done 0 1681304914 gatling.debug.users.allUsers.active 1 1681304914 gatling.debug.users.allUsers.waiting 0 1681304914 gatling.debug.users.allUsers.done 0 1681304914 gatling.debug.allRequests.ok.count 0 1681304914 gatling.debug.allRequests.ko.count 0 1681304914 gatling.debug.allRequests.all.count 0 1681304914 gatling.debug.myMethod.ok.count 0 1681304914 gatling.debug.myMethod.ko.count 0 1681304914 gatling.debug.myMethod.all.count 0 1681304914 
2023-04-12T13:08:34.707Z debugFailed to connect to Graphite server located at: localhost/127.0.0.1:2003
2023-04-12T13:08:35.643Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304915 gatling.debug.users.Group_grpc_test.waiting 0 1681304915 gatling.debug.users.Group_grpc_test.done 0 1681304915 gatling.debug.users.allUsers.active 1 1681304915 gatling.debug.users.allUsers.waiting 0 1681304915 gatling.debug.users.allUsers.done 0 1681304915 gatling.debug.allRequests.ok.count 0 1681304915 gatling.debug.allRequests.ko.count 0 1681304915 gatling.debug.allRequests.all.count 0 1681304915 gatling.debug.myMethod.ok.count 0 1681304915 gatling.debug.myMethod.ko.count 0 1681304915 gatling.debug.myMethod.all.count 0 1681304915 
2023-04-12T13:08:35.725Z debugFailed to connect to Graphite server located at: localhost/127.0.0.1:2003
2023-04-12T13:08:36.645Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304916 gatling.debug.users.Group_grpc_test.waiting 0 1681304916 gatling.debug.users.Group_grpc_test.done 0 1681304916 gatling.debug.users.allUsers.active 1 1681304916 gatling.debug.users.allUsers.waiting 0 1681304916 gatling.debug.users.allUsers.done 0 1681304916 gatling.debug.allRequests.ok.count 0 1681304916 gatling.debug.allRequests.ko.count 0 1681304916 gatling.debug.allRequests.all.count 0 1681304916 gatling.debug.myMethod.ok.count 0 1681304916 gatling.debug.myMethod.ko.count 0 1681304916 gatling.debug.myMethod.all.count 0 1681304916 
2023-04-12T13:08:36.748Z debugFailed to connect to Graphite server located at: localhost/127.0.0.1:2003
2023-04-12T13:08:37.643Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304917 gatling.debug.users.Group_grpc_test.waiting 0 1681304917 gatling.debug.users.Group_grpc_test.done 0 1681304917 gatling.debug.users.allUsers.active 1 1681304917 gatling.debug.users.allUsers.waiting 0 1681304917 gatling.debug.users.allUsers.done 0 1681304917 gatling.debug.allRequests.ok.count 0 1681304917 gatling.debug.allRequests.ko.count 0 1681304917 gatling.debug.allRequests.all.count 0 1681304917 gatling.debug.myMethod.ok.count 0 1681304917 gatling.debug.myMethod.ko.count 0 1681304917 gatling.debug.myMethod.all.count 0 1681304917 
2023-04-12T13:08:37.644Z debugAll connection/sending retries have been exhausted, ignore further messages

================================================================================
2023-04-12 16:08:37                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=1      KO=0     )
> myMethod                                                (OK=1      KO=0     )

---- Group grpc test -----------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================

2023-04-12T13:08:37.766Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:38.645Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304918 gatling.debug.users.Group_grpc_test.waiting 0 1681304918 gatling.debug.users.Group_grpc_test.done 0 1681304918 gatling.debug.users.allUsers.active 1 1681304918 gatling.debug.users.allUsers.waiting 0 1681304918 gatling.debug.users.allUsers.done 0 1681304918 gatling.debug.allRequests.ok.count 0 1681304918 gatling.debug.allRequests.ko.count 0 1681304918 gatling.debug.allRequests.all.count 0 1681304918 gatling.debug.myMethod.ok.count 0 1681304918 gatling.debug.myMethod.ko.count 0 1681304918 gatling.debug.myMethod.all.count 0 1681304918 
2023-04-12T13:08:38.645Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:39.645Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304919 gatling.debug.users.Group_grpc_test.waiting 0 1681304919 gatling.debug.users.Group_grpc_test.done 0 1681304919 gatling.debug.users.allUsers.active 1 1681304919 gatling.debug.users.allUsers.waiting 0 1681304919 gatling.debug.users.allUsers.done 0 1681304919 gatling.debug.allRequests.ok.count 0 1681304919 gatling.debug.allRequests.ko.count 0 1681304919 gatling.debug.allRequests.all.count 0 1681304919 gatling.debug.myMethod.ok.count 0 1681304919 gatling.debug.myMethod.ko.count 0 1681304919 gatling.debug.myMethod.all.count 0 1681304919 
2023-04-12T13:08:39.646Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:40.645Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304920 gatling.debug.users.Group_grpc_test.waiting 0 1681304920 gatling.debug.users.Group_grpc_test.done 0 1681304920 gatling.debug.users.allUsers.active 1 1681304920 gatling.debug.users.allUsers.waiting 0 1681304920 gatling.debug.users.allUsers.done 0 1681304920 gatling.debug.allRequests.ok.count 0 1681304920 gatling.debug.allRequests.ko.count 0 1681304920 gatling.debug.allRequests.all.count 0 1681304920 gatling.debug.myMethod.ok.count 0 1681304920 gatling.debug.myMethod.ko.count 0 1681304920 gatling.debug.myMethod.all.count 0 1681304920 
2023-04-12T13:08:40.645Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:41.644Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304921 gatling.debug.users.Group_grpc_test.waiting 0 1681304921 gatling.debug.users.Group_grpc_test.done 0 1681304921 gatling.debug.users.allUsers.active 1 1681304921 gatling.debug.users.allUsers.waiting 0 1681304921 gatling.debug.users.allUsers.done 0 1681304921 gatling.debug.allRequests.ok.count 0 1681304921 gatling.debug.allRequests.ko.count 0 1681304921 gatling.debug.allRequests.all.count 0 1681304921 gatling.debug.myMethod.ok.count 0 1681304921 gatling.debug.myMethod.ko.count 0 1681304921 gatling.debug.myMethod.all.count 0 1681304921 
2023-04-12T13:08:41.645Z debugAll connection/sending retries have been exhausted, ignore further messages

================================================================================
2023-04-12 16:08:42                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=1      KO=0     )
> myMethod                                                 (OK=1      KO=0     )

---- Group grpc test -----------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================

2023-04-12T13:08:42.646Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304922 gatling.debug.users.Group_grpc_test.waiting 0 1681304922 gatling.debug.users.Group_grpc_test.done 0 1681304922 gatling.debug.users.allUsers.active 1 1681304922 gatling.debug.users.allUsers.waiting 0 1681304922 gatling.debug.users.allUsers.done 0 1681304922 gatling.debug.allRequests.ok.count 0 1681304922 gatling.debug.allRequests.ko.count 0 1681304922 gatling.debug.allRequests.all.count 0 1681304922 gatling.debug.myMethod.ok.count 0 1681304922 gatling.debug.myMethod.ko.count 0 1681304922 gatling.debug.myMethod.all.count 0 1681304922 
2023-04-12T13:08:42.646Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:43.646Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304923 gatling.debug.users.Group_grpc_test.waiting 0 1681304923 gatling.debug.users.Group_grpc_test.done 0 1681304923 gatling.debug.users.allUsers.active 1 1681304923 gatling.debug.users.allUsers.waiting 0 1681304923 gatling.debug.users.allUsers.done 0 1681304923 gatling.debug.allRequests.ok.count 0 1681304923 gatling.debug.allRequests.ko.count 0 1681304923 gatling.debug.allRequests.all.count 0 1681304923 gatling.debug.myMethod.ok.count 0 1681304923 gatling.debug.myMethod.ko.count 0 1681304923 gatling.debug.myMethod.all.count 0 1681304923 
2023-04-12T13:08:43.646Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:44.643Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304924 gatling.debug.users.Group_grpc_test.waiting 0 1681304924 gatling.debug.users.Group_grpc_test.done 0 1681304924 gatling.debug.users.allUsers.active 1 1681304924 gatling.debug.users.allUsers.waiting 0 1681304924 gatling.debug.users.allUsers.done 0 1681304924 gatling.debug.allRequests.ok.count 0 1681304924 gatling.debug.allRequests.ko.count 0 1681304924 gatling.debug.allRequests.all.count 0 1681304924 gatling.debug.myMethod.ok.count 0 1681304924 gatling.debug.myMethod.ko.count 0 1681304924 gatling.debug.myMethod.all.count 0 1681304924 
2023-04-12T13:08:44.644Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:45.643Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304925 gatling.debug.users.Group_grpc_test.waiting 0 1681304925 gatling.debug.users.Group_grpc_test.done 0 1681304925 gatling.debug.users.allUsers.active 1 1681304925 gatling.debug.users.allUsers.waiting 0 1681304925 gatling.debug.users.allUsers.done 0 1681304925 gatling.debug.allRequests.ok.count 0 1681304925 gatling.debug.allRequests.ko.count 0 1681304925 gatling.debug.allRequests.all.count 0 1681304925 gatling.debug.myMethod.ok.count 0 1681304925 gatling.debug.myMethod.ko.count 0 1681304925 gatling.debug.myMethod.all.count 0 1681304925 
2023-04-12T13:08:45.644Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:46.645Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304926 gatling.debug.users.Group_grpc_test.waiting 0 1681304926 gatling.debug.users.Group_grpc_test.done 0 1681304926 gatling.debug.users.allUsers.active 1 1681304926 gatling.debug.users.allUsers.waiting 0 1681304926 gatling.debug.users.allUsers.done 0 1681304926 gatling.debug.allRequests.ok.count 0 1681304926 gatling.debug.allRequests.ko.count 0 1681304926 gatling.debug.allRequests.all.count 0 1681304926 gatling.debug.myMethod.ok.count 0 1681304926 gatling.debug.myMethod.ko.count 0 1681304926 gatling.debug.myMethod.all.count 0 1681304926 
2023-04-12T13:08:46.646Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:47.633Z debugMax duration of 15 seconds reached

================================================================================
2023-04-12 16:08:47                                          15s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=1      KO=0     )
> myMethod                                                 (OK=1      KO=0     )

---- Group grpc test -----------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================

2023-04-12T13:08:47.635Z debugGraphiteMetrics=gatling.debug.users.Group_grpc_test.active 1 1681304927 gatling.debug.users.Group_grpc_test.waiting 0 1681304927 gatling.debug.users.Group_grpc_test.done 0 1681304927 gatling.debug.users.allUsers.active 1 1681304927 gatling.debug.users.allUsers.waiting 0 1681304927 gatling.debug.users.allUsers.done 0 1681304927 gatling.debug.allRequests.ok.count 0 1681304927 gatling.debug.allRequests.ko.count 0 1681304927 gatling.debug.allRequests.all.count 0 1681304927 gatling.debug.myMethod.ok.count 0 1681304927 gatling.debug.myMethod.ko.count 0 1681304927 gatling.debug.myMethod.all.count 0 1681304927 
2023-04-12T13:08:47.635Z debugAll connection/sending retries have been exhausted, ignore further messages
2023-04-12T13:08:47.661Z debugStatsEngine was stopped
Simulation mytests.Debug completed in 15 seconds
2023-04-12T13:08:47.662Z debugAfter hook executed
2023-04-12T13:08:47.685Z debugRunning CoordinatedShutdown with reason [ActorSystemTerminateReason]
Parsing log file(s)...
2023-04-12T13:08:47.723Z debugCollected List(pathToProject/simulation.log) from debug-20230412130831060
2023-04-12T13:08:47.731Z debugFirst pass
2023-04-12T13:08:47.735Z debugFirst pass done: read 3 lines
2023-04-12T13:08:47.744Z debugSecond pass
2023-04-12T13:08:47.760Z debugSecond pass: read 3 lines
Parsing log file(s) done
Generating reports...`

**Comment by phiSgr** [comment]
Gatling version mismatch.

**Comment by KirillSefirov** [comment]
Can you tell me which versions should be? I tried a few, from your project, but the problem is the same
Thats my build gradle

plugins {
    id("io.gatling.gradle") version "3.9.2.1"
}

repositories {
    mavenCentral()
}

dependencies {
    gatling("com.github.phisgr:gatling-grpc-kt:0.15.1")
    gatling("ch.qos.logback.contrib:logback-janino-fragment:0.1.5")
    gatling("org.codehaus.janino:janino:3.1.8")
    gatling("com.github.phisgr:gatling-javapb-ijext:1.3.0")
}

**Comment by phiSgr** [comment]
`gatling-javapb-ijext` is unrelated. 

`gatling-grpc:0.16.0` is a compatibility update for gatling 3.9.x
`gatling-grpc-kt:0.15.1` is just a wrapper, and is compatible with `gatling-grpc:0.16.0` and `gatling-grpc:0.15.1`

See

https://github.com/phiSgr/gatling-grpc/issues/79#issuecomment-1490676091

**Comment by KirillSefirov** [comment]
Holy moly, it really works now, thank you so much!
