### ISSUE TITLE
Incompatible with Gatling 3.10.3

### ISSUE THREAD

**Issue by vas78** [phiSgr/gatling-grpc#88]
**Describe the bug**
The latest release 0.17.0 cannot be used with Gatling 3.10.3

**To Reproduce**
Run any simulation using grpc with Gatling 3.10.3, it fails with exception:
```
13:12:08.227 [WARN ] i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener@2a956b0
java.lang.ClassNotFoundException: io.gatling.jdk.util.StringBuilderPool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: io/gatling/jdk/util/StringBuilderPool
	at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.dump$1(GrpcCallAction.scala:155)
	at com.github.phisgr.gatling.grpc.action.GrpcCallAction$ContinuingListener.run(GrpcCallAction.scala:179)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
The simulation should run

**Environment:**
 - OS: OSX
 - Java: openjdk version "17.0.2" 2022-01-18
 - Versions:
   - Gatling-gRRC: 0.17.0
   - Kotlin binding version (if applicable): n/a
   - Gatling: 3.10.3
   - Launcher: zip bundle

**Additional context**
Probably related to [this change in Gatling](https://github.com/gatling/gatling/commit/da21af9a092bb63fa8fdd3b41fb0e838b801d19a#diff-2d03614d22c6bc3b8e24b81e19c1f39aea26373705715b7424b829cd28c0714eR17)

**Comment by nptri** [comment]
0.17.0 version is intended for Gatling 3.9.5
For Gatling 3.10.3, there were some changes in their code (obviously) => result in incompatible as the errors you are seeing.
You can downgrade Gatling and try again

**Comment by vas78** [comment]
Yes, sure, Gatling downgrade is the only way to continue using this plugin atm.
However, as far as I understood from a [previous similar issue](https://github.com/phiSgr/gatling-grpc/issues/72#issuecomment-1356082295), the general intention for this plugin is to support the latest Gatling version 😉

**Comment by ajax-demydov-k** [comment]
Add io.gatling:gatling-jdk-util:3.9.5 to deps and everything will be ok

**Comment by phiSgr** [comment]
Out of respect for Gatling Corp, I will not update my plugin and compete with their enterprise offering.
