### ISSUE TITLE
java.lang.NoSuchMethodError: io.gatling.core.Predef$._configuration_$eq(Lio/gatling/core/config/GatlingConfiguration;)V

### ISSUE THREAD

**Issue by ducquyen2509** [phiSgr/gatling-grpc#9]
java.lang.NoSuchMethodError: io.gatling.core.Predef$._configuration_$eq(Lio/gatling/core/config/GatlingConfiguration;)V
        at io.gatling.app.Runner.run0(Runner.scala:71)
        at io.gatling.app.Runner.run(Runner.scala:60)
        at io.gatling.app.Gatling$.start(Gatling.scala:73)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)
        at io.gatling.app.Gatling$.main(Gatling.scala:38)
        at io.gatling.app.Gatling.main(Gatling.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.NoSuchMethodError: io.gatling.core.Predef$._configuration_$eq(Lio/gatling/core/config/GatlingConfiguration;)V
        at io.gatling.app.Runner.run0(Runner.scala:71)
        at io.gatling.app.Runner.run(Runner.scala:60)
        at io.gatling.app.Gatling$.start(Gatling.scala:73)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)
        at io.gatling.app.Gatling$.main(Gatling.scala:38)
        at io.gatling.app.Gatling.main(Gatling.scala)

**Comment by phiSgr** [comment]
This stacktrace has nothing to do with my code. Anyway it is answered in [the previous issue](https://github.com/phiSgr/gatling-grpc/issues/8#issuecomment-496811033).

At the time of writing the latest version of Gatling is 3.1.2, please update.
